# Room constants
ROOM_NAME_MAX_LENGTH = 100
ROOM_VERBOSE_NAME = "Room"
ROOM_VERBOSE_NAME_PLURAL = "Rooms"
ROOM_ORDERING = ["name"]

# Message constants
MESSAGE_ORDERING = ["-timestamp"]
MESSAGE_CONTENT_PREVIEW_LENGTH = 50
MESSAGE_VERBOSE_NAME = "Message"
MESSAGE_VERBOSE_NAME_PLURAL = "Messages"
